### PR TITLE
Housekeeping

### PR DESCRIPTION
**Pull request by cabo**

### CODE REVIEW

**Review by thomas-fossati — APPROVED** [review]
LGTM, thanks!

**Comment by cabo** [comment]
Is there an easy way to check the ASN.1 snippets?

**Comment by cabo** [comment]
I'm also planning to turn all sourcecode types to lower case, as required in https://www.rfc-editor.org/materials/sourcecode-types.txt
Not sure of implications to Makefile etc.

**Comment by thomas-fossati** [comment]
> Is there an easy way to check the ASN.1 snippets?

not that I know of.  BTW, the way MessageImprint is described is non-ambiguous but completely custom.   ASN.1 "value notation" may be a better option.

**Comment by cabo** [comment]
But do we have a tool that can check ASN.1 value notation?  Maybe the fantasy notation is better, because it cannot be wrong :-)

**Comment by thomas-fossati** [comment]
> But do we have a tool that can check ASN.1 value notation?

Good question.  It appears that there is no open-source tool available for this :-(
NIH had an `asntool`, it looks it's no longer accessible.

> Maybe the fantasy notation is better, because it cannot be wrong :-)

:rofl:

Would using JER qualify as trolling ISO/ITU?

**Review by henkbirkholz — APPROVED** [review]
Thanks!

**Comment by cabo** [comment]
> Would using JER qualify as trolling ISO/ITU?

I like the idea, but let's do that in the next PR...

**Pull request merged**
